export const ADD_ITEM_CONSTRUCTOR = 'ADD_ITEM_CONSTRUCTOR' as const;
export const DELETE_ITEM_CONSTRUCTOR = 'DELETE_ITEM_CONSTRUCTOR' as const;
export const MOVE_ITEM_CONSTRUCTOR = 'MOVE_ITEM_CONSTRUCTOR' as const;
export const RESET_ITEM_CONSTRUCTOR = 'RESET_ITEM_CONSTRUCTOR' as const;
